name: api_practice
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_iconly: ^1.0.2
  card_swiper: ^3.0.1
  fancy_shimmer_image: ^2.0.3
  http: ^1.2.0
  flutter_login: ^5.0.0
  http_client: ^1.5.3
  dio: ^5.7.0
  crypto: ^3.0.3
  flutter_appauth: ^8.0.3
  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^3.1.2
  sqflite: ^2.3.2
  path: ^1.8.3
  country_picker: ^2.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/

android:
  applicationName: "api_practice"
  appAuthRedirectScheme: "com.example.apipractice"
